title: Alana Canann
description: >- # this means to ignore newlines until "baseurl:"
  This is the demo site for a Jekyll theme version of
  HTML5 UP's sleek, responsive site template Prologue.
author: Alana Canann
email: alana.canann@gmail.com
avatar: assets/images/alana.png

url: "//alanacanann.github.io"
base_url: "//alanacanann.github.io"

# Social settings
# Make sure to include the full url including protocol, e.g. https://github.com/chrisbobbe
linkedin_url: https://www.linkedin.com/in/alana-canann-39b53090
github_url: https://github.com/alanacanann
facebook_url: "https://www.facebook.com/alanacanann"
instagram_url: "https://www.instagram.com/alanacanann/?hl=en"

# Google Analytics Tracking ID goes here:
# google_analytics:

# The following settings are NECESSARY for the Prologue theme to run:

remote_theme: chrisbobbe/jekyll-theme-prologue
collections: [sections]
